-- MySQL Script generated by MySQL Workbench
-- Sun 09 Jan 2022 12:52:55 AM EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ORDER_PROCESSING_SYSTEM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ORDER_PROCESSING_SYSTEM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ORDER_PROCESSING_SYSTEM` ;
USE `ORDER_PROCESSING_SYSTEM` ;

-- -----------------------------------------------------
-- Table `ORDER_PROCESSING_SYSTEM`.`PUBLISHER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ORDER_PROCESSING_SYSTEM`.`PUBLISHER` (
  `name` VARCHAR(45) NOT NULL,
  `telephone_number` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `ID` INT NOT NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ORDER_PROCESSING_SYSTEM`.`BOOK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ORDER_PROCESSING_SYSTEM`.`BOOK` (
  `ISBN` VARCHAR(17) NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `PublisherID` INT NOT NULL,
  `PublicationYear` YEAR NOT NULL,
  `SellingPrice` DOUBLE NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `PUBLISHER_BOOK_NAME_FK_idx` (`PublisherID` ASC) VISIBLE,
  CONSTRAINT `PUBLISHER_BOOK_NAME_FK`
    FOREIGN KEY (`PublisherID`)
    REFERENCES `ORDER_PROCESSING_SYSTEM`.`PUBLISHER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ORDER_PROCESSING_SYSTEM`.`AUTHORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ORDER_PROCESSING_SYSTEM`.`AUTHORS` (
  `AuthorName` VARCHAR(45) NOT NULL,
  `AuthorID` INT NOT NULL,
  PRIMARY KEY (`AuthorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ORDER_PROCESSING_SYSTEM`.`LIBRARY_ORDER_DETAILS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ORDER_PROCESSING_SYSTEM`.`LIBRARY_ORDER_DETAILS` (
  `OrderID` INT NOT NULL,
  `BookISBN` VARCHAR(17) NOT NULL,
  `Quantity` INT NOT NULL,
  `RequestTime` DATE NOT NULL,
  `DeliveryTime` DATE NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `BOOK_ORDERDETAILS_BOOKID_FK_idx` (`BookISBN` ASC) VISIBLE,
  CONSTRAINT `BOOK_ORDERDETAILS_BOOKID_FK`
    FOREIGN KEY (`BookISBN`)
    REFERENCES `ORDER_PROCESSING_SYSTEM`.`BOOK` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ORDER_PROCESSING_SYSTEM`.`BOOK_COPIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ORDER_PROCESSING_SYSTEM`.`BOOK_COPIES` (
  `ISBN` VARCHAR(17) NOT NULL,
  `INStock` INT NOT NULL,
  `Threshold` INT NOT NULL,
  PRIMARY KEY (`ISBN`),
  CONSTRAINT `BOOK_BOOK_COPIES_ISBN_FK`
    FOREIGN KEY (`ISBN`)
    REFERENCES `ORDER_PROCESSING_SYSTEM`.`BOOK` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ORDER_PROCESSING_SYSTEM`.`BOOK_AUTHORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ORDER_PROCESSING_SYSTEM`.`BOOK_AUTHORS` (
  `ISBN` VARCHAR(17) NOT NULL,
  `AuthorID` INT NOT NULL,
  PRIMARY KEY (`ISBN`, `AuthorID`),
  INDEX `AUTHORS_BOOK_AUTHORS_ID_FK_idx` (`AuthorID` ASC) VISIBLE,
  CONSTRAINT `BOOK_BOOK_AUTHORS_ISBN_FK`
    FOREIGN KEY (`ISBN`)
    REFERENCES `ORDER_PROCESSING_SYSTEM`.`BOOK` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AUTHORS_BOOK_AUTHORS_ID_FK`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `ORDER_PROCESSING_SYSTEM`.`AUTHORS` (`AuthorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ORDER_PROCESSING_SYSTEM`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ORDER_PROCESSING_SYSTEM`.`USER` (
  `EMail` VARCHAR(45) NOT NULL,
  `Fname` VARCHAR(20) NOT NULL,
  `ID` INT NOT NULL,
  `Lname` VARCHAR(20) NOT NULL,
  `shipping_address` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `EMail_UNIQUE` (`EMail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ORDER_PROCESSING_SYSTEM`.`CART`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ORDER_PROCESSING_SYSTEM`.`CART` (
  `user_id` INT NOT NULL,
  `ISBN` VARCHAR(17) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`user_id`, `ISBN`),
  INDEX `ISBN_FK2_idx` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `userId_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `ORDER_PROCESSING_SYSTEM`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ISBN_FK2`
    FOREIGN KEY (`ISBN`)
    REFERENCES `ORDER_PROCESSING_SYSTEM`.`BOOK` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ORDER_PROCESSING_SYSTEM`.`BOOK_SALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ORDER_PROCESSING_SYSTEM`.`BOOK_SALES` (
  `userID` INT NOT NULL,
  `total_price` DOUBLE NOT NULL,
  `quantity` INT NOT NULL,
  `date` DATE NOT NULL,
  `ISBN` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`userID`),
  INDEX `BOOK_FK_idx` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `BOOK_FK`
    FOREIGN KEY (`ISBN`)
    REFERENCES `ORDER_PROCESSING_SYSTEM`.`BOOK` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `USER_FK`
    FOREIGN KEY (`userID`)
    REFERENCES `ORDER_PROCESSING_SYSTEM`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
